### ISSUE TITLE
Relies on authentication before the user is logged in

### ISSUE THREAD

**Issue by svandragt** [humanmade/hm-require-login#13]
The plugin is hooked into init and does a check for user capabilities (read capability), however the user isn't always logged in fully until the 'authenticate' hook is applied. 

In the case of the applications passwords feature of WP 5.6 the user has no capabilities of this point because the application passwords hasn't been authenticated, the current user is set at that point. Therefore the check will fail.

https://github.com/WordPress/wordpress-develop/pull/540/files#diff-4112a9a0bb18713bc2fc7868ceffe4403d765722f605e42b313ef2cdc218177fR433

**Comment by roborourke** [comment]
@svandragt it's not really clear to me what the app passwords flow is. I presume require login is just kicking in too early for a specific endpoint or URL that we need to add an exception for?

**Comment by roborourke** [comment]
Fixed by #14
